version: "3.2"

networks:
  redis:

services:
  bridge:
    image: outofcoffee/gefyra:${IMAGE_TAG:-latest}
    build: .
    environment:
      BRIDGE_CONFIG: "/etc/gefyra/config/queue_one_up_one_down.yaml"
    volumes:
      - "./examples:/etc/gefyra/config"
    networks:
      - redis

  upstream:
    image: bitnami/redis:4.0
    environment:
      REDIS_PASSWORD: "password"
    ports:
      - "6379:6379"
    networks:
      - redis

  downstream:
    image: bitnami/redis:4.0
    environment:
      REDIS_PASSWORD: "password"
    ports:
      - "6389:6379"
    networks:
      - redis
