name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Install dependencies
        run: go get
      - name: Test
        run: go test -v ./...
      - name: Build binary
        run: go build

      - name: Dry run - Build Docker image
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: docker build --tag outofcoffee/gefyra .

      - name: Dry run - Release binaries
        uses: goreleaser/goreleaser-action@v2
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release --snapshot

      - name: Release binaries
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: startsWith(github.ref, 'refs/tags/')
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: outofcoffee/gefyra

      - name: Build and push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
